version: "3.7"
services:
  nodejs:
    container_name: nodejs
    build: .
    ports:
      - "3000:3000"
    networks:
      - node_network
  node_db:
    image: mysql:5.7
    container_name: node_db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=kinuca01
      - MYSQL_DATABASE=moe_db
    networks:
      - node_network
networks:
  node_network:
    driver: bridge
